backend_poa_administracion/apps/Evaluacion/urls.py
from django.urls import path
from .views import ListarEvaluciones
from .views import GuardarEvaluacion
from .views import ListaEvaluacionGestionPeriodo
from .views import GuardarFormularioEvaluacion
from .views import GuardaresEvaluadoObjGestion
from .views import ListaFormulariosEvaluacion
from .views import ListaEvaluacionObjGestion
from .views import ListaFormulariosEvaluacionOPE
from .views import GuardarFormularioEvaluacionOPE
from .views import GuardaresEvaluadoOperacionFuncionamiento
from .views import ListaEvaluacionOperacionesFuncionamiento
from .views import ListaEvaluacionObjGestionUnidad
from .views import ListaEvaluacionOperacionesFuncionamientoUnidad
from .views import ActualizarEvaluacion

from .views import ListarEvalucionesAprobado
# from .views import ListaMedioVerificacionId
# from .views import actualizarMedioVerificacionFile
# from .views import actualizarAvance_1
# from .views import SiexisteSeguimientoGestion
# from .views import SumaTotalObjetivosGestion
# from .views import ListarSeguimientoEstado
# from .views import ListarSeguimientoGestionPeriodo
# # from .views import ListarSeguimientoGestionEstado
# from .views import ListarSeguimientoGestionPeriodoUnidad
# from .views import ListarSeguimientoGestion
# from .views import ListarSeguimientoUnidad
# from .views import ListarSeguimientoGestionEstadoPeriodo

urlpatterns = [
    path('ListarEvaluciones/', ListarEvaluciones.as_view(),name="ListarEvaluciones"),
    path('GuardarEvaluacion/', GuardarEvaluacion.as_view(),name="GuardarEvaluacion"),
    path('ListaEvaluacionGestionPeriodo/<int:gestion>/<int:periodo>/<int:idPOA>/', ListaEvaluacionGestionPeriodo.as_view(),name="ListaEvaluacionGestionPeriodo"),
    path('GuardarFormularioEvaluacion/', GuardarFormularioEvaluacion.as_view(),name="GuardarFormularioEvaluacion"),
    path('GuardaresEvaluadoObjGestion/', GuardaresEvaluadoObjGestion.as_view(),name="GuardaresEvaluadoObjGestion"),
    path('ListaFormulariosEvaluacion/<int:gestion>/<int:periodo>/<int:idE>/', ListaFormulariosEvaluacion.as_view(),name="ListaFormulariosEvaluacion"),
    path('ListaEvaluacionObjGestion/<int:idFormEva>/', ListaEvaluacionObjGestion.as_view(),name="ListaEvaluacionObjGestion"),
    path('ListaFormulariosEvaluacionOPE/<int:gestion>/<int:periodo>/<int:idE>/', ListaFormulariosEvaluacionOPE.as_view(),name="ListaFormulariosEvaluacionOPE"),
    path('GuardarFormularioEvaluacionOPE/', GuardarFormularioEvaluacionOPE.as_view(),name="GuardarFormularioEvaluacionOPE"),
    path('GuardaresEvaluadoOperacionFuncionamiento/', GuardaresEvaluadoOperacionFuncionamiento.as_view(),name="GuardaresEvaluadoOperacionFuncionamiento"),
    path('ListaEvaluacionOperacionesFuncionamiento/<int:idFormEva>/', ListaEvaluacionOperacionesFuncionamiento.as_view(),name="ListaEvaluacionOperacionesFuncionamiento"),
    path('ListaEvaluacionObjGestionUnidad/<int:idFormEva>/<int:idUnidad>/', ListaEvaluacionObjGestionUnidad.as_view(),name="ListaEvaluacionObjGestionUnidad"),
    path('ListaEvaluacionOperacionesFuncionamientoUnidad/<int:idFormEva>/<int:idUnidad>/', ListaEvaluacionOperacionesFuncionamientoUnidad.as_view(),name="ListaEvaluacionOperacionesFuncionamientoUnidad"),
    path('ActualizarEvaluacion/<int:pk>/', ActualizarEvaluacion.as_view(),name="ActualizarEvaluacion"),
    path('ListarEvalucionesAprobado/', ListarEvalucionesAprobado.as_view(),name="ListarEvalucionesAprobado"),
    
    # path('ListaMedioVerificacionId/<int:id>/', ListaMedioVerificacionId.as_view(),name="ListaMedioVerificacionId"),
    # path('actualizarMedioVerificacionFile/<int:pk>/', actualizarMedioVerificacionFile.as_view(),name="actualizarMedioVerificacionFile"),
    # path('actualizarAvance_1/<int:pk>/', actualizarAvance_1.as_view(),name="actualizarAvance_1"),
    # path('SiexisteSeguimientoGestion/<int:gestion>/<int:unidad>/', SiexisteSeguimientoGestion.as_view(),name="SiexisteSeguimientoGestion"),
    # path('SumaTotalObjetivosGestion/<int:id>/', SumaTotalObjetivosGestion.as_view(),name="SumaTotalObjetivosGestion"),
    # path('ListarSeguimientoEstado/', ListarSeguimientoEstado.as_view(),name="ListarSeguimientoEstado"),
    # path('ListarSeguimientoGestionPeriodo/<int:gestion>/<str:periodo>/', ListarSeguimientoGestionPeriodo.as_view(),name="ListarSeguimientoGestionPeriodo"),
    # # path('ListarSeguimientoGestionEstado/<int:gestion>/<str:periodicidad>/<str:periodo>/', ListarSeguimientoGestionEstado.as_view(),name="ListarSeguimientoGestionEstado"),
    # path('ListarSeguimientoGestionPeriodoUnidad/<int:gestion>/<str:periodo>/<int:pkUnidad>/', ListarSeguimientoGestionPeriodoUnidad.as_view(),name="ListarSeguimientoGestionPeriodoUnidad"),
    # path('ListarSeguimientoGestion/<int:gestion>/', ListarSeguimientoGestion.as_view(),name="ListarSeguimientoGestion"),
    # path('ListarSeguimientoUnidad/<int:idUnidad>/', ListarSeguimientoUnidad.as_view(),name="ListarSeguimientoUnidad"),
    # path('ListarSeguimientoGestionEstadoPeriodo/<int:gestion>/<int:periodo>/', ListarSeguimientoGestionEstadoPeriodo.as_view(),name="ListarSeguimientoGestionEstadoPeriodo"),
    
    


]

backend_poa_administracion/apps/Poai/urls.py
from django.urls import path
from .views import DatosPOAi,GuardarPOAi,DatosPOAiDetalle,DatosPOAiDetalleUnidad,cambioEstadoPOA,ListaPOAiGestionEstado
from .views import ListaPOAiEstado
from .views import ListaPOAiEstadoUnidad
from .views import ListaPOAGestionEstado
from .views import ListaFormularioPoai
from .views import ListaPoasGestionUnidad
from .views import ListaPoasGestionUnidad_1
from .views import DatosPOAiDetalleUnidadReform
from .views import ListaPOAGestionVersion
from .views import ListaPOAiEstadoNotificacion
from .views import ListaPoasGestionUnidad_v1

urlpatterns = [
    path('DatosPOAi/', DatosPOAi.as_view(),name="DatosPOAi"),
    path('GuardarPOAi/', GuardarPOAi.as_view(),name="GuardarPOAi"),
    path('DatosPOAiDetalle/<int:gestion>/<int:unidad>/', DatosPOAiDetalle.as_view(),name="DatosPOAiDetalle"),
    path('DatosPOAiDetalleUnidad/<int:unidad>/', DatosPOAiDetalleUnidad.as_view(),name="DatosPOAiDetalleUnidad"),
    path('cambioEstadoPOA/<int:pk>/', cambioEstadoPOA.as_view(), name="cambioEstadoPOA"),
    path('ListaPOAiGestionEstado/<int:gestion>/', ListaPOAiGestionEstado.as_view(),name="ListaPOAiGestionEstado"),
    path('ListaPOAiEstado/', ListaPOAiEstado.as_view(),name="ListaPOAiEstado"),
    path('ListaPOAiEstadoUnidad/<int:idunidad>/', ListaPOAiEstadoUnidad.as_view(),name="ListaPOAiEstadoUnidad"),
    path('ListaPOAGestionEstado/<str:estado>/<int:gestion>/', ListaPOAGestionEstado.as_view(),name="ListaPOAGestionEstado"),
    path('ListaFormularioPoai/<int:id>/', ListaFormularioPoai.as_view(),name="ListaFormularioPoai"),
    path('ListaPoasGestionUnidad/<int:gestion>/<int:unidad>/<int:version>/', ListaPoasGestionUnidad.as_view(),name="ListaPoasGestionUnidad"),
    path('ListaPoasGestionUnidad_1/<int:unidad>/<int:gestion>/', ListaPoasGestionUnidad_1.as_view(),name="ListaPoasGestionUnidad_1"),
    path('DatosPOAiDetalleUnidadReform/<int:unidad>/', DatosPOAiDetalleUnidadReform.as_view(),name="DatosPOAiDetalleUnidadReform"),
    path('ListaPOAGestionVersion/<str:estado>/<int:gestion>/<int:version>/', ListaPOAGestionVersion.as_view(),name="ListaPOAGestionVersion"),
    path('ListaPOAiEstadoNotificacion/', ListaPOAiEstadoNotificacion.as_view(),name="ListaPOAiEstadoNotificacion"),
    path('ListaPoasGestionUnidad_v1/<int:unidad>/', ListaPoasGestionUnidad_v1.as_view(),name="ListaPoasGestionUnidad_v1"),
]

backend_poa_administracion/users/urls.py
from django.urls import path

from backend_poa_administracion.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from rest_framework_jwt.views import obtain_jwt_token
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Pastebin API')
urlpatterns = [
    url(r'^$', schema_view),
    #urls del subistema
    path('v1/', include('apps.Formulacion.urls')),
    path('v1/', include('apps.responsablesInformacion.urls')),
    path('v1/', include('apps.ElaboradoSSU.urls')),
    path('v1/', include('apps.Poai.urls')),
    path('v1/', include('apps.Listas_para_Formulacion.urls')),
    path('v1/', include('apps.Formularios_Complementarios.urls')),
    path('v1/', include('apps.POA_General.urls')),
    path('v1/', include('apps.ProcesoRevision.urls')),
    path('v1/', include('apps.administracionFechas.urls')),
    path('v1/', include('apps.Seguimiento.urls')),
    path('v1/', include('apps.periodicidad.urls')),
    path('v1/', include('apps.SeguimientoOperacion.urls')),
    path('v1/', include('apps.SeguimientoGeneral.urls')),
    path('v1/', include('apps.ParametrosEvaluacion.urls')),
    path('v1/', include('apps.Evaluacion.urls')),
    path('v1/', include('apps.Reformulacion.urls')),
    # path('v1/', include('apps.uploadapp.urls')),
    path('token-auth/', obtain_jwt_token),
    path('core/', include('apps.Usuarios_Login.urls')),
    #urls del subistema
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("backend_poa_administracion.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

backend_poa_administracion/apps/ElaboradoSSU/models.py
from django.db import models
from ..Formulacion.models import formularios
from ..POA_General.models import FormulariosGenerales
# # Create your models here.

class PersonalRevisor(models.Model):
    AbreviacionProf= models.CharField(max_length=30)
    Nombre = models.CharField(max_length=50)
    Apellidos=models.CharField(max_length=200)
    Cargo=models.CharField(max_length=100)
    Estado_CHOICES= (
    ('Activo', 'Activo'),
    ('Inactivo', 'Inactivo')
    )
    Estado= models.CharField(max_length=20, choices=Estado_CHOICES, default='',blank=True)
    prioridadM=models.IntegerField()
    def __str__(self):
        return str(self.pk)
    class Meta:
        ordering = ('Apellidos')
    class Meta:
        verbose_name_plural = ("Personal Revisor - SSU")

class PersonalAprobacion(models.Model):
    AbreviacionProf= models.CharField(max_length=30)
    Nombre = models.CharField(max_length=50)
    Apellidos=models.CharField(max_length=200)
    Cargo=models.CharField(max_length=100)
    Estado_CHOICES= (
    ('Activo', 'Activo'),
    ('Inactivo', 'Inactivo')
    )
    Estado= models.CharField(max_length=20, choices=Estado_CHOICES, default='',blank=True)
    def __str__(self):
        return str(self.pk)
    class Meta:
        ordering = ('Apellidos')
    class Meta:
        verbose_name_plural = ("Personal Aprobacion - SSU")

#tabla para personal revisado n:m    
class RevisadoPor(models.Model):
    formulario=models.ForeignKey(formularios,on_delete=models.CASCADE)
    personalR=models.ForeignKey(PersonalRevisor,on_delete=models.CASCADE)
    Gestion = models.IntegerField()
    FechaElaboracion=models.DateField(auto_now=True)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("FN-Revisado por - Formulario")

# tabla para personal aprobado n:m 
class AprobadoPor(models.Model):
    formulario=models.ForeignKey(formularios,on_delete=models.CASCADE)
    personalA=models.ForeignKey(PersonalAprobacion,on_delete=models.CASCADE)
    Gestion = models.IntegerField()
    FechaElaboracion=models.DateField(auto_now=True)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("FN-Aprobado por - Formulario")

#tabla para personal revisado n:m GENERAL   
class RevisadoPorGeneral(models.Model):
    formulario=models.ForeignKey(FormulariosGenerales,on_delete=models.CASCADE)
    personalR=models.ForeignKey(PersonalRevisor,on_delete=models.CASCADE)
    Gestion = models.IntegerField()
    FechaElaboracion=models.DateField(auto_now=True)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("FG-Revisado por - Formulario General")

# tabla para personal aprobado n:m GENERAL
class AprobadoPorGeneral(models.Model):
    formulario=models.ForeignKey(FormulariosGenerales,on_delete=models.CASCADE)
    personalA=models.ForeignKey(PersonalAprobacion,on_delete=models.CASCADE)
    Gestion = models.IntegerField()
    FechaElaboracion=models.DateField(auto_now=True)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("FG-Aprobado por - Formulario General")

backend_poa_administracion/apps/Formularios_Complementarios/models.py
from django.db import models
from ..responsablesInformacion.models import Unidad
from ..Poai.models import POAi
#Modelo para crear la tabla de Acciones a corto plazo prueba
class accionesCortoPlazo(models.Model):
    id = models.IntegerField(primary_key=True)
    CMedianoPlazo=models.CharField(max_length=50)
    CCortoPlazo=models.CharField(max_length=500)
    CAccionesEspecificas=models.CharField(max_length=50)
    DescripcionACP = models.CharField(max_length=500)
    Resultado = models.CharField(max_length=500)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("Acciones Corto Plazo (Objetivos Institucionales)")

#indicadores  de acuerdo a las acciones a corto plazo
class indicador(models.Model):
    id = models.IntegerField(primary_key=True)
    Codigo=models.IntegerField()
    Denominacion = models.CharField(max_length=500)
    LineaBase=models.IntegerField(default=0)
    MetaGestion=models.IntegerField(default=0)
    MedioVerificacion=models.CharField(max_length=500)
    UnidadResponsable=models.CharField(max_length=500)  #porque este campo verificar
    ProgFisicaT1er = models.CharField(max_length=100)
    ProgFisicaT2do = models.CharField(max_length=100)
    ProgFisicaT3er = models.CharField(max_length=100)
    ProgFisicaT4to = models.CharField(max_length=100)
    IdAccionCortoPlazo=models.ForeignKey(accionesCortoPlazo,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("Indicadores")

# simulacion de una tabla temporal para el guardado de los indicadores seleccionados
class indicadoresSeleccionados(models.Model):
    idIndicadorS=models.ForeignKey(indicador,on_delete=models.CASCADE)   #esto es la lleve foranea del indicador 
    valor = models.CharField(max_length=50)
    gestion=models.IntegerField(default=0)
    idUnidad=models.ForeignKey(Unidad,on_delete=models.PROTECT)
    idPOA=models.ForeignKey(POAi,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("Indicadores Seleccionados")

backend_poa_administracion/apps/Reformulacion/models.py
from django.db import models
from ..responsablesInformacion.models import Personal
from ..POA_General.models import POAGeneral
# Create your models here.

class AprobacionReformulacion(models.Model):
    FechaElaboracion=models.DateField(auto_now=True)
    Descripcion = models.CharField(max_length=500)
    PoaGeneral=models.ForeignKey(POAGeneral,on_delete=models.CASCADE)
    PersonalResposanble=models.ForeignKey(Personal,on_delete=models.CASCADE)
    adjunto=models.FileField(blank=True, null=True)
    def __str__(self):
        return str(self.pk)
    class Meta:
        verbose_name_plural = ("Detalle Aprobacion Reformulacion")

backend_poa_administracion/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

backend_poa_administracion/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}backend_POA_administracion{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">backend_POA_administracion</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 